from __future__ import annotations

"""榴莲电商售后规则知识库（结构化，供 Agent 命中与输出）。"""

PROBLEM_TYPES: dict[str, str] = {
    "bad_fruit": "坏果/破损",
    "unripe": "过生/夹生",
    "overripe": "过熟",
    "logistics_delay": "物流延迟",
    "weight_short": "重量不足",
    "presale_ship": "预售发货",
    "refund_compensation": "退款赔付",
    "general": "一般售后咨询",
}

CLASSIFIER_KEYWORDS: dict[str, list[str]] = {
    "bad_fruit": ["坏果", "坏了", "破损", "发霉", "变质", "烂了", "虫", "裂开", "流汁发黑"],
    "unripe": ["过生", "太生", "夹生", "不熟", "硬块", "发白"],
    "overripe": ["过熟", "太熟", "发酸", "酒味", "发黑流汁"],
    "logistics_delay": ["物流", "延迟", "没送到", "快递慢", "超时", "迟迟不到"],
    "weight_short": ["重量不足", "缺斤", "分量不够", "不够秤", "轻了"],
    "presale_ship": ["预售", "什么时候发", "还没发货", "发货时间", "多久能到"],
    "refund_compensation": ["退款", "赔付", "理赔", "退钱", "赔偿"],
}

AFTER_SALE_RULES: list[dict] = [
    {
        "id": "rule_as_001",
        "title": "签收后24小时坏果反馈",
        "problem_types": ["bad_fruit", "overripe"],
        "keywords": ["24小时", "签收", "坏果", "破损"],
        "priority": "P0",
        "required_evidence": ["order_id", "sign_time", "fruit_photos", "problem_desc"],
        "handling": "核实签收时间在24小时内后，引导用户提交坏果/过熟照片与问题说明，可先行部分退款或补发评估。",
        "cs_reply": "已收到您的反馈。请在签收24小时内提供订单号、签收时间、榴莲整体/果肉特写照片，我们核实后会尽快处理退款或补发。",
        "escalate": False,
    },
    {
        "id": "rule_as_002",
        "title": "图片凭证要求",
        "problem_types": ["bad_fruit", "unripe", "overripe", "weight_short"],
        "keywords": ["照片", "图片", "凭证", "拍照"],
        "priority": "P0",
        "required_evidence": ["fruit_photos", "package_photos"],
        "handling": "需包含外包装、溯源码标签、果肉状态特写；重量问题需附称重照片。",
        "cs_reply": "麻烦您补充：1）外包装全貌 2）包装上的批次溯源码 3）果肉状态特写；若是重量问题请附称重照片。",
        "escalate": False,
    },
    {
        "id": "rule_as_003",
        "title": "过生/夹生判定与处理",
        "problem_types": ["unripe"],
        "keywords": ["过生", "夹生", "太生"],
        "priority": "P1",
        "required_evidence": ["order_id", "fruit_photos", "problem_desc"],
        "handling": "结合批次成熟度区间判断；明显夹生且在合理窗口内反馈可走换货/部分退款，需人工复核。",
        "cs_reply": "过生问题需要结合批次成熟度区间判断。请提供订单号和果肉照片，我们会安排专人复核后给出换货或退款方案。",
        "escalate": True,
    },
    {
        "id": "rule_as_004",
        "title": "过熟/变质处理",
        "problem_types": ["overripe", "bad_fruit"],
        "keywords": ["过熟", "变质", "发酸"],
        "priority": "P0",
        "required_evidence": ["order_id", "sign_time", "fruit_photos"],
        "handling": "签收24小时内、照片清晰显示过熟变质，优先退款或补发；超时效按规则降级处理。",
        "cs_reply": "若签收在24小时内且果肉明显过熟变质，请发照片给我们，核实后可安排退款或补发。",
        "escalate": False,
    },
    {
        "id": "rule_as_005",
        "title": "重量误差规则",
        "problem_types": ["weight_short"],
        "keywords": ["重量", "缺斤", "不够秤"],
        "priority": "P1",
        "required_evidence": ["order_id", "weight_photos", "problem_desc"],
        "handling": "允许±3% 合理误差；超出部分按差额比例退款，需称重照片与订单规格对照。",
        "cs_reply": "请提供带秤的称重照片和订单规格信息。误差在±3%内属正常，超出部分我们会按规则退款。",
        "escalate": False,
    },
    {
        "id": "rule_as_006",
        "title": "物流延迟规则",
        "problem_types": ["logistics_delay"],
        "keywords": ["物流", "延迟", "超时"],
        "priority": "P1",
        "required_evidence": ["order_id"],
        "handling": "查询物流节点；超承诺时效可协商优惠券或退款，严重延迟转人工跟进。",
        "cs_reply": "我先帮您查物流进度。若超过承诺送达时间，可申请延迟补偿或退款，复杂情况会转专员跟进。",
        "escalate": True,
    },
    {
        "id": "rule_as_007",
        "title": "预售发货规则",
        "problem_types": ["presale_ship"],
        "keywords": ["预售", "发货"],
        "priority": "P2",
        "required_evidence": ["order_id"],
        "handling": "预售单按商品页标注发货日期执行；未到期不视为违约，到期未发可退款。",
        "cs_reply": "预售订单会按商品页标注日期发货。若已过承诺发货日仍未发出，您可以申请全额退款。",
        "escalate": False,
    },
    {
        "id": "rule_as_008",
        "title": "退款赔付通用流程",
        "problem_types": ["refund_compensation"],
        "keywords": ["退款", "赔付", "理赔"],
        "priority": "P1",
        "required_evidence": ["order_id", "problem_desc"],
        "handling": "先分类问题类型再匹配规则；材料齐全走自动审核，争议单转人工。",
        "cs_reply": "退款需要先确认订单和问题类型。请提供订单号并描述具体情况，我会按规则帮您处理。",
        "escalate": False,
    },
    {
        "id": "rule_as_009",
        "title": "订单号定位原则",
        "problem_types": ["general"],
        "keywords": ["订单", "定位"],
        "priority": "P1",
        "required_evidence": ["order_id"],
        "handling": "售后以订单号为主定位；批次溯源码一批多订单，不能单独作为售后凭证。",
        "cs_reply": "售后需要订单号才能准确定位您的购买记录，请提供订单号（如 ORD_10001）。",
        "escalate": False,
    },
]

EVIDENCE_LABELS: dict[str, str] = {
    "order_id": "订单号",
    "sign_time": "签收时间",
    "fruit_photos": "榴莲果肉/整体照片",
    "package_photos": "外包装照片",
    "weight_photos": "称重照片",
    "problem_desc": "问题文字描述",
}
