"""演示商品、批次溯源、订单种子数据（写入 PostgreSQL）。"""

from __future__ import annotations

TRACE_BATCHES: dict[str, dict] = {
    "TR20260608001": {
        "valid": True,
        "batch_id": "BATCH_8891",
        "batch_name": "6月8日马来入库",
        "variety": "猫山王",
        "grade": "A",
        "origin": "马来西亚彭亨",
        "pick_date": "2026-06-06",
        "stock_in_date": "2026-06-08",
        "weight_range": "3-4斤",
        "ripeness_range": "75%-85%",
        "qty_in_batch": 120,
        "inspection_result": "合格",
        "cold_chain_status": "全程冷链",
        "batch_status": "on_sale",
        "listing_ids": ["sku_201"],
    },
    "TR20260609002": {
        "valid": True,
        "batch_id": "BATCH_8892",
        "batch_name": "6月9日泰国入库",
        "variety": "金枕",
        "grade": "A",
        "origin": "泰国东部",
        "pick_date": "2026-06-07",
        "stock_in_date": "2026-06-09",
        "weight_range": "5-6斤",
        "ripeness_range": "70%-80%",
        "qty_in_batch": 200,
        "inspection_result": "合格",
        "cold_chain_status": "全程冷链",
        "batch_status": "on_sale",
        "listing_ids": ["sku_101", "sku_102"],
    },
    "TR20260607003": {
        "valid": True,
        "batch_id": "BATCH_8890",
        "batch_name": "6月7日越南入库",
        "variety": "干尧",
        "grade": "A",
        "origin": "越南平顺",
        "pick_date": "2026-06-05",
        "stock_in_date": "2026-06-07",
        "weight_range": "4-5斤",
        "ripeness_range": "72%-82%",
        "qty_in_batch": 80,
        "inspection_result": "合格",
        "cold_chain_status": "全程冷链",
        "batch_status": "on_sale",
        "listing_ids": ["sku_301"],
    },
    "TR20260610004": {
        "valid": True,
        "batch_id": "BATCH_8893",
        "batch_name": "6月10日槟城黑刺入库",
        "variety": "黑刺",
        "grade": "A",
        "origin": "马来西亚槟城",
        "pick_date": "2026-06-08",
        "stock_in_date": "2026-06-10",
        "weight_range": "3-4斤",
        "ripeness_range": "78%-88%",
        "qty_in_batch": 45,
        "inspection_result": "合格",
        "cold_chain_status": "全程冷链",
        "batch_status": "on_sale",
        "listing_ids": ["sku_401"],
    },
}

PRODUCTS: dict[str, dict] = {
    "sku_101": {
        "product_id": "sku_101",
        "name": "金枕榴莲 A级 5-6斤",
        "variety": "金枕",
        "grade": "A",
        "price": 268,
        "stock": 45,
        "ship_time": "今日下单，预计明日送达",
        "taste_tags": ["偏甜", "气味适中"],
        "feature_tags": ["偏甜", "气味适中", "适合新手", "聚会分享"],
        "sales_score": 92,
        "sales_rank": 1,
        "trace_code": "TR20260609002",
        "batch_summary": {
            "origin": "泰国东部",
            "stock_in_date": "2026-06-09",
            "grade": "A",
            "ripeness_range": "70%-80%",
        },
        "image": "/static/durian-golden.jpg",
    },
    "sku_102": {
        "product_id": "sku_102",
        "name": "金枕榴莲 A级 3-4斤",
        "variety": "金枕",
        "grade": "A",
        "price": 198,
        "stock": 32,
        "ship_time": "今日下单，预计明日送达",
        "taste_tags": ["偏甜", "气味适中"],
        "feature_tags": ["偏甜", "气味适中", "小份尝鲜", "高性价比"],
        "sales_score": 78,
        "sales_rank": 3,
        "trace_code": "TR20260609002",
        "batch_summary": {
            "origin": "泰国东部",
            "stock_in_date": "2026-06-09",
            "grade": "A",
            "ripeness_range": "70%-80%",
        },
        "image": "/static/durian-golden.jpg",
    },
    "sku_201": {
        "product_id": "sku_201",
        "name": "猫山王榴莲 A级 3-4斤",
        "variety": "猫山王",
        "grade": "A",
        "price": 358,
        "stock": 18,
        "ship_time": "今日下单，预计明日送达",
        "taste_tags": ["苦甜", "绵密", "气味浓郁"],
        "feature_tags": ["苦甜", "绵密", "风味浓郁", "老饕首选"],
        "sales_score": 74,
        "sales_rank": 4,
        "trace_code": "TR20260608001",
        "batch_summary": {
            "origin": "马来西亚彭亨",
            "stock_in_date": "2026-06-08",
            "grade": "A",
            "ripeness_range": "75%-85%",
        },
        "image": "/static/durian-musang.jpg",
    },
    "sku_301": {
        "product_id": "sku_301",
        "name": "干尧榴莲 A级 4-5斤",
        "variety": "干尧",
        "grade": "A",
        "price": 228,
        "stock": 26,
        "ship_time": "今日下单，预计后日送达",
        "taste_tags": ["偏甜", "细腻"],
        "feature_tags": ["偏甜", "细腻", "气味温和", "进阶尝鲜"],
        "sales_score": 81,
        "sales_rank": 2,
        "trace_code": "TR20260607003",
        "batch_summary": {
            "origin": "越南平顺",
            "stock_in_date": "2026-06-07",
            "grade": "A",
            "ripeness_range": "72%-82%",
        },
        "image": "/static/durian-golden.jpg",
    },
    "sku_401": {
        "product_id": "sku_401",
        "name": "黑刺榴莲 A级 3-4斤",
        "variety": "黑刺",
        "grade": "A",
        "price": 428,
        "stock": 12,
        "ship_time": "今日下单，预计明日送达",
        "taste_tags": ["苦甜", "绵密", "脂香浓郁"],
        "feature_tags": ["苦甜", "绵密", "顶奢品种", "老饕首选", "槟城直采"],
        "sales_score": 88,
        "sales_rank": 5,
        "trace_code": "TR20260610004",
        "batch_summary": {
            "origin": "马来西亚槟城",
            "stock_in_date": "2026-06-10",
            "grade": "A",
            "ripeness_range": "78%-88%",
        },
        "image": "/static/durian-musang.jpg",
    },
}

ORDERS: dict[str, dict] = {
    "ORD_10001": {
        "order_id": "ORD_10001",
        "user_id": "demo_user",
        "status": "delivered",
        "items": [{"product_id": "sku_101", "name": "金枕榴莲 A级 5-6斤", "qty": 1}],
        "trace_codes": ["TR20260609002"],
        "created_at": "2026-06-09T14:30:00",
        "total_amount": 268,
    },
    "ORD_10002": {
        "order_id": "ORD_10002",
        "user_id": "demo_user",
        "status": "delivered",
        "items": [{"product_id": "sku_201", "name": "猫山王榴莲 A级 3-4斤", "qty": 1}],
        "trace_codes": ["TR20260608001"],
        "created_at": "2026-06-08T10:00:00",
        "total_amount": 358,
    },
}
